version: '3.9'

services:
  api:
    build:
      context: ./BackendAPI
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
    env_file:
      - ./BackendAPI/.env
    restart: always

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./flutter_web_app/build/web:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    restart: always
